import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { cn } from '@/lib/cn';
import Header from '@/components/header';

import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const RootLayout = ({
	children
}: Readonly<{
	children: React.ReactNode;
}>) => (
	<html lang="en">
		<body className={cn('flex min-h-screen flex-col', inter.className)}>
			<Providers>
				<Header />
				<main className="container mx-auto flex h-full flex-1 flex-col">
					{children}
				</main>
			</Providers>
		</body>
	</html>
);

export default RootLayout;
